### ISSUE TITLE
3.5.1 won't work

### ISSUE THREAD

**Issue by asmetanka** [keremciu/sketch-select-invisible-layers#2]

**Comment by jydesign** [comment]
Hi, this works in v 3.6.1, but only if using infinite canvas. Once an artboard is in use on a page, it no longer works. Do you have any plans to update this to support artboards? It is very useful when it does function. thank you.

**Comment by keremciu** [comment]
Hello @jydesign 

I don't remember anything about this plugin but I will try to update :)

**Comment by keremciu** [comment]
@asmetanka @jydesign I've updated the plugin, you can try the new version? I hope you like it
